macOS dual arch (Intel & M1) builds with Carthage
Mantle/Mantle pull request #888
Opened 2021-08-29 14:26 UTC by petrmifek

Recently (~XCode 12.5) Mantle was preventing our project to archive due to a missing/disabled arm architecture support on **macOS** (debugging on Intel works, but dual architecture **archiving for Intel and M1 fails**). Mantle Carthage project for macOS is also using the **VALID_ARCHS** setting for that restriction, which **has been deprecated since XCode 12**.

Here are few quick fixes and updates we had to make:
- update the xcconfigs to latest (as a "side effect" also update the Nimble and Quick submodules to match Cartfile.resolved)
- switch the xcconfigs from "Mac OS" to the new "macOS" variants

These changes then required (likely due a stricter defaults in xcconfigs) a few changes to the code - mostly mismatched nullability issues. They are separated in commits, may be that the last one regarding the class_getProperty should go to a macro somewhere, as it repeats those lines like 5x. If so, I'd be happy to add that if someone could point me a suitable header file where to put those.

Thanks!

2021-09-01 18:17 UTC, robb commented
Hi, thanks for looking into this.

There seems to be a white space issue with the `class_getProperty` changes – Mantle uses tabs.

Also, do you think you could investigate the  tests failing? A quick look makes it seem like Nimble and Quick aren't building.

2021-09-02 16:44 UTC, petrmifek commented
Ah, thanks, thought that was just my local issue the tests failing, unfortunately that wasn't the case :)

Please try now. Quick and Nimble needed to be upgraded plus a few things similar to the main code.

2021-09-02 16:55 UTC, robb requested changes
Looking good, just a few minor nits.

2021-09-02 16:55 UTC, robb commented on Mantle/MTLJSONAdapter.m
> +                    NSLocalizedFailureReasonErrorKey: ex.reason == nil ? @"" : ex.reason,
Can I bother you with one more whitespace pass? Xcode used to pick up the tabs preference from the project file, not sure if that broke…

```suggestion
					NSLocalizedFailureReasonErrorKey: ex.reason == nil ? @"" : ex.reason,
```

2021-09-02 16:55 UTC, robb commented on Mantle/NSError+MTLModelException.m
> +        NSLocalizedFailureReasonErrorKey: exception.reason == nil ? @"" : exception.reason,
```suggestion
		NSLocalizedFailureReasonErrorKey: exception.reason == nil ? @"" : exception.reason,
```

2021-09-02 16:55 UTC, robb commented on Mantle/NSError+MTLModelException.m
> +        NSLocalizedFailureReasonErrorKey: exception.reason == nil ? @"" : exception.reason,
Also, I think you can use the `?:` pattern to get rid of `nil`s here.

```suggestion
		NSLocalizedFailureReasonErrorKey : exception.reason ?: @"",
```

2021-09-02 16:55 UTC, robb commented on MantleTests/MTLTestModel.m
> +		@"nestedName": externalRepresentation[@"nested"][@"name"] == nil ? [NSNull null] : externalRepresentation[@"nested"][@"name"],
As above.

```suggestion
		@"name": externalRepresentation[@"username"] ?: [NSNull null],
		@"nestedName": externalRepresentation[@"nested"][@"name"] ?: [NSNull null],
```

2021-09-02 16:56 UTC, robb commented
Seems like the tests a going to base (2/5 still in progress as of now…)

2021-09-02 22:01 UTC, petrmifek commented
Thanks! Here you go... Hopefully this time all the spaces are away. Must've confused it with some copy-pastes or what...

2021-09-06 08:04 UTC, robb approved these changes
Looks good! 💖

2021-09-06 08:05 UTC, merged